baseURL = 'http://policymodellingati.org/'
languageCode = 'en-us'
title = 'Policy Modelling Theme @ The Alan Turing Institute'
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
# fancyTitle = '<img height="128" src="/images/screenshot.png" alt="Policy Modelling Theme"/>' # title for frontpage, may include image
fancyTitle = 'Policy Modelling Theme' # title for frontpage, may include image
copyright = "K. R. Fair"
description = 'Public Policy Programme<br /><a href="https://www.turing.ac.uk/">The Alan Turing Institute</a>'
# startbuttonText = "Go somewhere"
# startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = [stuff]

[[params.menu.main]]
url = '/'
title = "Home"

# [[params.menu.main]]
# url = '/people/'
# title = "People"

[[params.menu.main]]
url = '/projects/project1'
title = "Project 1"

[[params.menu.main]]
url = '/publications/'
title = "Publications"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Meet the team'
body = '''

<br/><br/>

| {{< figure src="/images/oag.jpg" width="200px" >}} | {{< figure src="/images/oag.jpg" width="200px" >}} |  {{< figure src="/images/oag.jpg" width="200px" >}} |  {{< figure src="/images/oag.jpg" width="200px" >}} |  {{< figure src="/images/oag.jpg" width="200px" >}} | 
|  :---:  |  :---:  |  :---:  |  :---:  |  :---:  | 
| [Omar A. Guererro](../people/person1) | [Daniele Guariso](../people/person1) | [Hardik Rajpal](../people/person1) | [Kathyrn R. Fair](../people/person1) | [Tuong Vu](../people/person1) | 
| {{< figure src="/images/oag.jpg" width="200px" >}} | {{< figure src="/images/oag.jpg" width="200px" >}} |  {{< figure src="/images/oag.jpg" width="200px" >}} |  {{< figure src="/images/oag.jpg" width="200px" >}} |  {{< figure src="/images/oag.jpg" width="200px" >}} | 
| [Leonardo Castro Gonzalez](../people/person1) | [Alejandro Beltran](../people/person1) | [Zach Kessler](../people/person1) | [David Meine](../people/person1) | [Santiago Musalem Pinto](../people/person1) |
'''

#[[params.one.icon]]
#icon = "fa-diamond"
#style = "1"
#label = "Lorem"

#[[params.one.icon]]
#icon = "fa-heart-o"
#style = "2"
#label = "Ipsum"

#[[params.one.icon]]
#icon = "fa-code"
#style = "3"
#label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "/images/oag.jpg"
#title = ''
body = '''
## [Project 1](../projects/project1)
Short project description 
'''

[params.three]
enable = true
title = 'Publications'
body = '''
* [Quantifying the Technological Foundations of Economic Complexity (2023)](https://arxiv.org/abs/2301.04579)
'''

#[[params.three.feature]]
#icon = "fa-paper-plane-o"
#title = "Arcu accumsan"
#body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

#[params.cta]
#enable = true
#title = "Arcue ut vel commodo"
#body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
#href = "#"
#text = "Learn More"
#special = false

#[params.contact]
#enable = true
#title = "Contact"
#body = "Leave us a message."
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
##phone = "+49 (0) 030 000 000"
#email = "nospam@example.com"
#subject = "New Submission!"
#formspree_form_id = "example_invalid"

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""