baseURL = 'http://turingcss.org/'
languageCode = 'en-us'
title = 'CSS Group @ The Alan Turing Institute'
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
# fancyTitle = '<img height="128" src="/images/screenshot.png" alt="Policy Modelling Theme"/>' # title for frontpage, may include image
fancyTitle = 'Computational Social Science Group' # title for frontpage, may include image
copyright = "The Alan Turing Institute"
description = 'A research collective at <a href="https://www.turing.ac.uk/" target="_blank">The Alan Turing Institute</a>'
extended = "The CSS group is an interdisciplinary team working in the development and application of computational methods to tackle major social science challenges. We work closely with governments and international organisations to translate our research into tools that are useful to policymakers. The CSS group is part of the Turing's <a href=https://www.turing.ac.uk/research/research-programmes/public-policy target=_blank>Public Policy Programme</a>, and is also known as the 'Modelling for Policy Theme'."

# startbuttonText = "Go somewhere"
# startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = [stuff]

#[[params.menu.main]]
#title = "Home"
#url = '/'

# [[params.menu.main]]
# url = '/people/'
# title = "People"



[[params.menu.main]]
url = '/projects/firms_fringe'
title = "Detecting Firms' Fringe Behaviour"

[[params.menu.main]]
url = '/projects/endogenous_production_network'
title = "Endogenous Production Networks"

[[params.menu.main]]
url = '/projects/gov_media'
title = "Government & Media Behaviour"

[[params.menu.main]]
url = '/projects/housing_market'
title = "Housing Market Dynamics"

[[params.menu.main]]
url = '/projects/labour_flow_networks'
title = "Labour Flow Networks"

[[params.menu.main]]
url = 'http://policypriority.org'
title = "Policy Priority Inference"

[[params.menu.main]]
url = '/projects/tech_sophistication'
title = "Quantifying Technological Sophistication"

[[params.menu.main]]
url = '/projects/skills_complexity'
title = "Skill Interaction and Complexity"

[[params.menu.main]]
url = '/projects/tech_sophistication'
title = "Skill Sorting and Productivity"

[[params.menu.main]]
url = '/projects/various'
title = "Various Projects"



#[[params.menu.main]]
#url = '/publications/'
#title = "Publications"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Researchers'
body = '''

<br/><br/>

| {{< figure src="/images/people/oag.jpg" width="250px" >}} | {{< figure src="/images/people/aperson.jpg" width="250px" >}} |  {{< figure src="/images/people/aperson.jpg" width="250px" >}} |  {{< figure src="/images/people/krf.png" width="250px" >}} |
|  :---:  |  :---:  |  :---:  |  :---:  |  
| [Omar A. Guerrero (Group Head)](../people/oag) | [Daniele Guariso](../people/person1) | [Hardik Rajpal](../people/person1) | [Kathyrn R. Fair](../people/krf) | 
|   {{< figure src="/images/people/tmvu.jpeg" width="250px" >}} | {{< figure src="/images/people/ab.jpg" width="250px" >}} |  {{< figure src="/images/people/zbk.jpeg" width="250px" >}}|  {{< figure src="/images/people/aperson.jpg" width="250px" >}} |
| [Tuong Vu](../people/tmvu) |[Alejandro Beltran](../people/ab) | [Zachary B. Kessler](../people/zbk)| [Leonardo Castro Gonzalez](../people/person1) | 
'''



[params.oneb]
enable = true
title = 'Research Assistants'
body = '''

<br/><br/>

| {{< figure src="/images/aperson.jpg" width="250px" >}} |  {{< figure src="/images/aperson.jpg" width="250px" >}} | 
|  :---:  |  :---:  | 
| [David Meine](../people/person1) | [Santiago Musalem Pinto](../people/person1) |
'''



[[params.cta.link]]
#href = "#"
#text = "Learn More"
#special = false

#[params.contact]
#enable = true
#title = "Contact"
#body = "Leave us a message."
#address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
##phone = "+49 (0) 030 000 000"
#email = "nospam@example.com"
#subject = "New Submission!"
#formspree_form_id = "example_invalid"

#[params.social]
#twitter = ""
#facebook = ""
#instagram = ""
#dribble = ""
